version: "3.8"

volumes:
  grafana_data: {}
  prometheus_data: {}

networks:
  monitor:
    driver: bridge

x-monitor: &monitor
  networks:
    - monitor
  restart: unless-stopped

services:
  caddy:
    <<: *monitor
    image: caddy:latest
    container_name: caddy
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH:-$2a$14$1l.IozJx7xQRVmlkEQ32OeEEfP5mRxTpbDTCTcXRqn19gXD8YK1pO}
    volumes:
      - ./services/caddy:/etc/caddy
    ports:
      - 3000:3000
      - 8080:8080
      - 9090:9090

  cadvisor:
    <<: *monitor
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /cgroup:/cgroup:ro
      - /var/run:/var/run:ro
      - /var/lib/docker:/var/lib/docker:ro
    expose:
      - 8080

  grafana:
    <<: *monitor
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./data/crypto_trading.db:/app/crypto_trading.db
      - ./services/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./services/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    expose:
      - 3000

  node-exporter:
    <<: *monitor
    image: prom/node-exporter:latest
    container_name: node-exporter
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - /:/rootfs:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
    expose:
      - 9100

  prometheus:
    <<: *monitor
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=200h"
      - "--web.enable-lifecycle"
    volumes:
      - prometheus_data:/prometheus
      - ./services/prometheus:/etc/prometheus
    expose:
      - 9090