version: "3"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_SERVER_HTTP_PORT=3000
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./data/crypto_trading.db:/app/crypto_trading.db
      - ./static/dashboard.json:/app/dashboard.json
      - ./static/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./static/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
    ports:
      - 3000:3000
    restart: unless-stopped

  sqlitebrowser:
    image: ghcr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - CUSTOM_PORT=8080
    volumes:
      - ./data:/data
      - ./data/config:/config
    ports:
      - 8080:8080
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_AUTHKEY=tskey-auth-kgN6Rf7CNTRL-tR48sLp9PhW2FZ2G1Ju1hWxyqtXc96tCT
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped    