version: "3"

services:
  backend:
    image: jmy12k3/crypto-miner
    container_name: crypto_trading
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    command: python -m project
    restart: unless-stopped

  api:
    image: jmy12k3/crypto-miner
    container_name: crypto_trading_api
    working_dir: /app
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - 5000:5000
    command: gunicorn project.api_server:app -k eventlet -w 1 --threads 1 -b 0.0.0.0:5000
    depends_on:
      - backend
    restart: unless-stopped

  caddy:
    extends:
      file: common-services.yml
      service: caddy
    profiles:
      - monitor

  cadvisor:
    extends:
      file: common-services.yml
      service: cadvisor
    profiles:
      - monitor

  grafana:
    extends:
      file: common-services.yml
      service: grafana
    profiles:
      - monitor

  node-exporter:
    extends:
      file: common-services.yml
      service: node-exporter
    profiles:
      - monitor

  prometheus:
    extends:
      file: common-services.yml
      service: prometheus
    profiles:
      - monitor
