version: "3.9"

x-build: &build
  image: jmy12k3/binance_miner
  working_dir: /app
  volumes:
    - ./config:/app/config
    - ./data:/app/data
    - ./logs:/app/logs
  restart: unless-stopped

services:
  backend:
    <<: *build
    container_name: binance_miner
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m binance_miner

  api:
    <<: *build
    depends_on:
      - backend
    container_name: binance_miner_api
    ports:
      - 5000:5000
    command: uvicorn binance_miner.api_server:app --workers 1 --host 0.0.0.0 --port 5000
