version: "3.9"

x-build: &build
  build: .
  working_dir: /app
  volumes:
    - ./config:/app/config
    - ./data:/app/data
    - ./logs:/app/logs
  restart: unless-stopped

services:
  backend:
    <<: *build
    container_name: crypto_trading
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m project

  api:
    <<: *build
    depends_on:
      - backend
    container_name: crypto_trading_api
    ports:
      - 5000:5000
    command: uvicorn project.api_server:app --workers 1 --host 0.0.0.0 --port 5000
