version: "3.9"

x-build: &build
  build: .
  working_dir: /app
  volumes:
    - ./config:/app/config
    - ./data:/app/data
    - ./logs:/app/logs
  restart: unless-stopped

services:
  backend:
    <<: *build
    container_name: binance_miner
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m binance_miner

  api:
    <<: *build
    depends_on:
      - backend
    container_name: binance_miner_api
    ports:
      - 5000:5000
    command: >
      gunicorn binance_miner.api_server:app --worker-class uvicorn.workers.UvicornWorker --workers 1 --threads 1 --bind 0.0.0.0:5000
