version: "3.8"

x-build: &build
  build: .
  working_dir: /app
  volumes:
    - ./config:/app/config
    - ./data:/app/data
    - ./logs:/app/logs
  restart: unless-stopped

services:
  backend:
    <<: *build
    container_name: crypto_trading
    environment:
      - PYTHONUNBUFFERED=1
    command: python -m project

  api:
    <<: *build
    depends_on:
      - backend
    container_name: crypto_trading_api
    ports:
      - 5000:5000
    command: gunicorn project.api_server:app -k eventlet -w 1 --threads 1 -b 0.0.0.0:5000
